generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: docs.docker.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan  2 23:59:59 2027 GMT
  hsts: true
  hsts_max_age: 31536000
domains:
- domain: docker.com
  dnssec: false
  caa:
  - 0 issue "letsencrypt.org"
  - 0 issue "pki.goog"
  - 0 issue "sectigo.com"
  - 0 iodef "mailto:infra+caa-iodef@docker.com"
  - 0 issue "amazon.com"
  - 0 issue "comodoca.com"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
